apiVersion: batch/v1
kind: CronJob
metadata:
  name: ods-batch
spec:
  schedule: "00 18 * * *" 
  jobTemplate:
    spec:
      backoffLimit: 6
      activeDeadlineSeconds: 3600
      ttlSecondsAfterFinished: 100
    spec:
      template:
        spec:
          serviceAccountName: ods
          containers:
          - name: ods
            image: /:cae19c
            imagePullPolicy: Always
            command:
            - /bin/bash
            - -c
            - date;pip install psycopg2;/usr/bin/python3 test.py
            resources:
              limits:
                memory: "8000Mi"
          restartPolicy: OnFailure
